name: Changelog Generator
on:
  push:
    branches:
      - main
jobs:
  generate:
    name: Changelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create changelog
        uses: ./changelog-generator
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: /home/runner/work/_temp/_github_home/CHANGELOG.md
  upload:
    name: Upload Changelog to PR
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Download results from the generate job
        uses: actions/download-artifact@v2
        with:
          name: changelog
      - name: Add artifact to repo
        run: |
          git config --global user.name "Gerardo Grinman"
          git config --global user.email "ggrinman@gmail.com"
          git add --all
          git commit -m "docs: Generated Changelog for PR"
          git push
